### ISSUE TITLE
Get the Data of in the input field

### ISSUE THREAD

**Issue by Simsal** [hannaholl/angular-input-dropdown#1]
Hey there,

can you give me a hint, how to store the data of the input field, in order to use it within a $http.post?

TY

**Comment by hannaholl** [comment]
Hi there,

To access the actual value of the input field you have to set the `filter-list-method` attribute on the directive like this:

``` html
<input-dropdown filter-list-method="myController.filterDropdown(userInput)"></input-dropdown>
```

and then create the `filterDropdown(userInput)` method on your controller:

``` js
this.filterDropdown = function(userInput) {}
```

This method will be called every time the user types in the input field, the `userInput` parameter holds the input field's value and you can store this or use it in a http request. See the last section of the readme for a full example of this.

If instead you want to access the object the user selected from the dropdown list, you need to first create a property on your controller to store the value:

``` js
this.selectedObject = null;
```

then use the `selected-item` attribute and pass in the property you just created:

``` html
<input-dropdown selected-item="myController.selectedObject"></input-dropdown>
```

Now, when the user selects an item from the dropdown list the `selectedObject` property should be updated to match the user's selection (ie the new value of the input field, along with some other data if you're using a dropdown with objects instead of strings).

If you want to be notified when a selection has been made you can pass a method with the `item-selected-method` attribute:

``` html
<input-dropdown item-selected-method="myController.userSelectedItem(item)"></input-dropdown>
```

`userSelectedItem(item)` will now be called every time the user selects an item from the dropdown. Use the `item` parameter or the property you passed in the `selected-item` attribute to read the user's selection.

Hope this helps! Please let me know if you need anything else.
