### ISSUE TITLE
Return a newly entered user value

### ISSUE THREAD

**Issue by joseugs** [hannaholl/angular-input-dropdown#2]
You nailed it right there, would be even more useful if you can also have the option to return a newly entered value which is not in the dropdown list.

**Comment by alinnert** [comment]
I want to use this directive as a search field that displays suggestions in a drop down. But the user should also be able to enter their own search term.

**Comment by hannaholl** [comment]
Hi,

This is a great idea! When I originally built this module it was for a form where it was required that the user picked one of the options available from the list, but it makes more sense to also return the user input when using it as a normal search field.

I have started implementing this in [this branch here](https://github.com/hannaholl/angular-input-dropdown/tree/return-user-input).

To enable it, add the additional attribute `allow-custom-input="true"` to the markup.

This will make the field validate any user input (as well as items picked from the drop down list). At the moment there is no callback to the controller when the user enters anything in the field. I wasn't sure if this would be useful since you should be able to read the normal value of the input when the form is submitted anyway?

Please feel free to try the code on the branch out and let me know what you think. After I've had some more time to test it I will update the readme and merge into master.

Cheers!

**Comment by nirajkrz** [comment]
i wanted to add ngMessages to this and display error messages for validations like maxlength/require etc as well for the required field. any suggestions?

**Comment by Geetakokate** [comment]
hannaholl, How can I get the input entered by user in controller.

**Comment by hannaholl** [comment]
Hi all,

I've added this functionality here https://github.com/hannaholl/angular-input-dropdown/commit/7210e8f82f62fa58c2dab7ccb419b82ffcd6bc92.

Here is documentation on how to use it https://github.com/hannaholl/angular-input-dropdown#custom-user-intup

@Geetakokate To get the input entered by the user, you can now read the value the same way you would read it from a normal input field. Let me know if you have any more questions!

**Comment by hannaholl** [comment]
@nirajkrz I haven't worked enough with ngMessages to know the best way to implement them here. You could look at adding them to the directive template and see if that works? https://github.com/hannaholl/angular-input-dropdown/blob/master/inputDropdown.js#L4

To add validations for maxlength and other attributes, I think you would need to create more custom attributes on the directive and then transfer them to the `<input>` tag the same way I did with the `inputName` attribute: https://github.com/hannaholl/angular-input-dropdown/blob/master/inputDropdown.js#L5

One way to validate them would be to check for them inside the validator in the if statement here: https://github.com/hannaholl/angular-input-dropdown/blob/master/inputDropdown.js#L232

Or it might be better to simply remove `input-dropdown-validator` from the input field when `allowCustomInput` is set to `true` and let Angular to it's normal validation.

Let me know if you manage add ngMessages and more validation to the field. Feel free to create a PR if you find a good solution. If you want to discuss this more please create a new issue for it.

Thanks!

**Comment by nirajkrz** [comment]
Thanks @hannaholl , I added the validations on input field and used the attributes on directive to pass the applicable values to it:

```
<input type="text"
                name="{{inputName}}"
                placeholder="{{inputPlaceholder}}"
                ng-model="inputValue"
                ng-required="inputRequired"
                ng-maxlength="maxLength"
                ng-minLength="minLength"
                ng-change="inputChange()"
                ng-focus="inputFocus()"
                ng-blur="inputBlur($event)"
                input-dropdown-validator>

```

using ng-messages from my app, i was able to show the error messages.

Thanks for the suggestions!

**Comment by hannaholl** [comment]
I'm happy that worked @nirajkrz
Thanks for letting me know!
